[package]
name = "UpSet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.6"
bit-vec = "0.6.3"
clap = { version = "4.4.7", features = ["derive"] }
rand = "0.8.5"
seq_io = "0.3.2"
